services:
  pgcomments:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=commentdb
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
    ports:
      - '5434:5432'
    networks:
      - 'nw'
    restart: unless-stopped
    volumes:
      - pgcomments:/var/lib/postgresql/data

  pgacomments:
    container_name: commentpga
    image: 'dpage/pgadmin4'
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@pgadmin.com'
      PGADMIN_DEFAULT_PASSWORD: 'abcd1234'
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5051:80"
    depends_on:
      - 'pgcomments'
    networks:
      - 'nw'
    restart: unless-stopped
    volumes:
      - pgacomments:/var/lib/pgadmin

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: commentservice
    ports:
      - "8082:8082"
    networks:
      - 'nw'
    restart: unless-stopped

volumes:
  pgacomments:
  pgcomments:

networks:
  nw:
    driver: bridge
