
server:
  port: 8082

spring:
  application:
    name: comments
  datasource:
    url: jdbc:postgresql://pgcomments:5432/commentdb
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'

  rabbitmq:
    host: my-rabbitmq
    port: 5672
    username: guest
    password: guest

logging:
  level:
    org.hibernate.SQL: DEBUG
